"""first start

Revision ID: 74dc1c9558dc
Revises: 
Create Date: 2024-01-18 15:49:45.036916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74dc1c9558dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('verif', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('win', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonus', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_nft', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('rare', sa.String(), nullable=False),
    sa.Column('duel', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('arena', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name_nft')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfts')
    op.drop_table('users')
    # ### end Alembic commands ###
