"""nft withdraw

Revision ID: 53fa2c7ca21f
Revises: aadff3a72576
Create Date: 2024-02-26 15:31:24.892973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fa2c7ca21f'
down_revision: Union[str, None] = 'aadff3a72576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfts', sa.Column('withdraw', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfts', 'withdraw')
    # ### end Alembic commands ###
