"""rare int

Revision ID: d679bc4fa89c
Revises: 347a156cb13b
Create Date: 2024-01-21 23:24:03.715599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd679bc4fa89c'
down_revision: Union[str, None] = '347a156cb13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfts', 'rare',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    postgresql_using='rare::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfts', 'rare',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False,
                    postgresql_using='rare::varchar')
    # ### end Alembic commands ###
