"""nft telegram_id constraint

Revision ID: 347a156cb13b
Revises: 1f75bd79d1ae
Create Date: 2024-01-20 00:22:01.551746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347a156cb13b'
down_revision: Union[str, None] = '1f75bd79d1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nfts_user_id_fkey', 'nfts', type_='foreignkey')
    op.create_foreign_key(None, 'nfts', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nfts', type_='foreignkey')
    op.create_foreign_key('nfts_user_id_fkey', 'nfts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
