"""full

Revision ID: 3d42a896888b
Revises: 
Create Date: 2024-03-15 23:16:42.736782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d42a896888b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('win', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_address', sa.String(), nullable=False),
    sa.Column('dst_address', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_nft', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('activated', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('rare', sa.Integer(), nullable=False),
    sa.Column('duel', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('arena', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('withdraw', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name_nft')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('player_l_id', sa.Integer(), nullable=False),
    sa.Column('player_r_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_l_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_r_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('nfts')
    op.drop_table('withdrawals')
    op.drop_table('users')
    # ### end Alembic commands ###
