"""telegram_id

Revision ID: 1f75bd79d1ae
Revises: f52d39a5b519
Create Date: 2024-01-20 00:21:21.162057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f75bd79d1ae'
down_revision: Union[str, None] = 'f52d39a5b519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'verif',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.alter_column('users', 'verif',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
