"""Withdrawals

Revision ID: 0db3f0f8886b
Revises: 26b4695b9b48
Create Date: 2024-02-05 10:52:49.192171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db3f0f8886b'
down_revision: Union[str, None] = '26b4695b9b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_address', sa.String(), nullable=False),
    sa.Column('dst_address', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    # ### end Alembic commands ###
