"""nft activated

Revision ID: 2af6b20927d9
Revises: d679bc4fa89c
Create Date: 2024-01-24 02:44:38.782929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af6b20927d9'
down_revision: Union[str, None] = 'd679bc4fa89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfts', sa.Column('activated', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfts', 'activated')
    # ### end Alembic commands ###
